package model;
// Generated 21/09/2015 18:15:09 by Hibernate Tools 4.3.1



/**
 * Radreply generated by hbm2java
 */
public class Radreply  implements java.io.Serializable {


     private int id;
     private String username;
     private String attribute;
     private String op;
     private String value;

    public Radreply() {
    }

    public Radreply(int id, String username, String attribute, String op, String value) {
       this.id = id;
       this.username = username;
       this.attribute = attribute;
       this.op = op;
       this.value = value;
    }
    public Radreply(String username, String attribute, String op, String value) {
       this.id = 0;
       this.username = username;
       this.attribute = attribute;
       this.op = op;
       this.value = value;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
    public String getOp() {
        return this.op;
    }
    
    public void setOp(String op) {
        this.op = op;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString()
    {
        return "Radreply{" + "id=" + id + ", username=" + username + ", attribute=" + attribute + ", op=" + op + ", value=" + value + '}';
    }

    


}


